baseURL: https://mgealgeria.netlify.app/
title: MGE
author: username
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
theme: tella
enableRobotsTXT: yes
params:
  googleFonts: yes
  homepage_meta_tags:
    meta_description: A Hugo Theme for OSSProject, Companies, Organization...
    meta_og_description: A Hugo Theme for OSSProject, Companies, Organization...
    meta_og_image: https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png
    meta_og_title: MGE
    meta_og_type: website
    meta_og_url: https://tella.pages.dev
    meta_twitter_card: summary_large_image
    meta_twitter_creator: '@username'
    meta_twitter_site: '@username'
  icon:
    fontawesome: yes
  logo:
    alt: Tella Logo
    main: img/logo/logo.png
    size: h-14
  mainSections: blog
  showBlog: yes
  site:
    name: MGE
menu:
  footer:
    - name: Page d'acceuil
      url: /
      weight: 1
    - name: Linkedin
      pre: <i class='fab fa-linkedin text-2xl'></i>
      url: https://www.linkedin.com/
      weight: 2
    - name: Twitter
      pre: <i class='icon-twitter text-2xl'></i>
      url: https://twitter.com/
      weight: 3
    - name: Instagrem
      pre: <i class='fab fa-instagram text-2xl'></i>
      url: https://www.instagram.com/
      weight: 4
  main:
    - identifier: products
      name: Produits
      url: /products/
      weight: 1
    - identifier: about
      name: Qui sommes nous?
      url: /about/
      weight: 3
    - identifier: contact
      name: Contactez nous
      url: /contact/
      weight: 4
